### ISSUE TITLE
Maven coming back with an error on clean install

### ISSUE THREAD

**Issue by nitzanwilnai** [caelum/mamute#127] opened 2014-12-22 20:00 UTC
[ec2-user@ip-10-185-193-93 ~]$ git clone https://github.com/caelum/mamute.git
Cloning into 'mamute'...
remote: Counting objects: 44016, done.
remote: Total 44016 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (44016/44016), 43.92 MiB | 7.75 MiB/s, done.
Resolving deltas: 100% (22238/22238), done.
Checking connectivity... done.

[ec2-user@ip-10-185-193-93 ~]$ cd mamute/

[ec2-user@ip-10-185-193-93 mamute]$  mvn clean package -DskipTests
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for br.com.caelum:mamute:war:1.3.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.jacoco:jacoco-maven-plugin @ line 798, column 12
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-war-plugin @ line 869, column 12
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.codehaus.mojo:exec-maven-plugin @ line 874, column 12
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-clean-plugin is missing. @ line 901, column 12
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building mamute 1.3.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for br.com.caelum:vraptor:jar:4.0.0-beta-4-SNAPSHOT is missing, no dependency information available
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ mamute ---
[INFO] 
[INFO] --- maven-timestamp-plugin:1.0:create (default) @ mamute ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.6.2.201302030002:prepare-agent (default) @ mamute ---
[INFO] argLine set to -javaagent:/home/ec2-user/.m2/repository/org/jacoco/org.jacoco.agent/0.6.2.201302030002/org.jacoco.agent-0.6.2.201302030002-runtime.jar=destfile=/home/ec2-user/mamute/target/jacoco.exec
[INFO] 
[INFO] --- build-helper-maven-plugin:1.1:add-source (add-source) @ mamute ---
[INFO] Source directory: /home/ec2-user/mamute/src/main/migrations added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ mamute ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 31 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ mamute ---
[INFO] Compiling 301 source files to /home/ec2-user/mamute/src/main/webapp/WEB-INF/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Failure executing javac, but could not parse the error:
javac: invalid target release: 1.7
Usage: javac <options> <source files>
use -help for a list of possible options

[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:28 min
[INFO] Finished at: 2014-12-22T19:58:09+00:00
[INFO] Final Memory: 19M/45M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project mamute: Compilation failure
[ERROR] Failure executing javac, but could not parse the error:
[ERROR] javac: invalid target release: 1.7
[ERROR] Usage: javac <options> <source files>
[ERROR] use -help for a list of possible options
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by MatejBalantic** [comment] 2015-01-10 17:01
Having same problems with trying to run Mamute in IntelliJ:

```
17:59:22  INFO [StdSchedulerFactory ] Using default implementation for ThreadExecutor
17:59:22  INFO [SimpleThreadPool    ] Job execution threads will use class loader of thread: main
17:59:22  INFO [SchedulerSignalerImpl] Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
17:59:22  INFO [QuartzScheduler     ] Quartz Scheduler v.2.1.5 created.
17:59:22  INFO [RAMJobStore         ] RAMJobStore initialized.
17:59:22  INFO [QuartzScheduler     ] Scheduler meta-data: Quartz Scheduler (v2.1.5) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

17:59:22  INFO [StdSchedulerFactory ] Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
17:59:22  INFO [StdSchedulerFactory ] Quartz scheduler version: 2.1.5
17:59:22  INFO [QuartzConfigurator  ] Quartz configurator initializing...
17:59:22  INFO [MamuteDatabaseConfiguration] Loading hibernate xml from file://devel/mamute/src/main/webapp/WEB-INF/classes/production/hibernate.cfg.xml
log4j:WARN No appenders could be found for logger (com.mchange.v2.log.MLog).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
17:59:32  INFO [QuartzConfigurator  ] Invoking quartz configurator at http://localhost:8100/jobs/configure
17:59:32  INFO [HttpMethodDirector  ] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
17:59:32  INFO [HttpMethodDirector  ] Retrying request
17:59:32  INFO [HttpMethodDirector  ] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
17:59:32  INFO [HttpMethodDirector  ] Retrying request
17:59:32  INFO [HttpMethodDirector  ] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
17:59:32  INFO [HttpMethodDirector  ] Retrying request
17:59:32 ERROR [QuartzConfigurator  ] Could not configure quartz!
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:280)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at br.com.caelum.vraptor.quartzjob.QuartzConfigurator$StartQuartz.run(QuartzConfigurator.java:78)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MatejBalantic** [comment] 2015-01-10 17:04
Having same problems with trying to run Mamute in IntelliJ, but it seems that only when I run ``VRAPTOR_ENV=production ``

```
18:03:30  INFO [StdSchedulerFactory ] Using default implementation for ThreadExecutor
18:03:30  INFO [SimpleThreadPool    ] Job execution threads will use class loader of thread: main
18:03:30  INFO [SchedulerSignalerImpl] Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
18:03:30  INFO [QuartzScheduler     ] Quartz Scheduler v.2.1.5 created.
18:03:30  INFO [RAMJobStore         ] RAMJobStore initialized.
18:03:30  INFO [QuartzScheduler     ] Scheduler meta-data: Quartz Scheduler (v2.1.5) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

18:03:30  INFO [StdSchedulerFactory ] Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
18:03:30  INFO [StdSchedulerFactory ] Quartz scheduler version: 2.1.5
18:03:30  INFO [QuartzConfigurator  ] Quartz configurator initializing...
18:03:31  INFO [MamuteDatabaseConfiguration] Loading hibernate xml from file:/devel/mamute/src/main/webapp/WEB-INF/classes/production/hibernate.cfg.xml
log4j:WARN No appenders could be found for logger (com.mchange.v2.log.MLog).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
18:03:40  INFO [QuartzConfigurator  ] Invoking quartz configurator at http://localhost:8100/jobs/configure
18:03:40  INFO [HttpMethodDirector  ] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
18:03:40  INFO [HttpMethodDirector  ] Retrying request
18:03:40  INFO [HttpMethodDirector  ] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
18:03:40  INFO [HttpMethodDirector  ] Retrying request
18:03:40  INFO [HttpMethodDirector  ] I/O exception (java.net.ConnectException) caught when processing request: Connection refused
18:03:40  INFO [HttpMethodDirector  ] Retrying request
18:03:40 ERROR [QuartzConfigurator  ] Could not configure quartz!
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at java.net.Socket.connect(Socket.java:528)
	at java.net.Socket.<init>(Socket.java:425)
	at java.net.Socket.<init>(Socket.java:280)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at br.com.caelum.vraptor.quartzjob.QuartzConfigurator$StartQuartz.run(QuartzConfigurator.java:78)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by MatejBalantic** [comment] 2015-01-10 17:25
It looks like it might be this:
https://github.com/caelum/vraptor-quartzjob/commit/8ecf12b496a349c5854a370b49e11daa3f74eb99

**Comment by csokol** [comment] 2015-01-10 18:12
I think you're right, that's why this issue is only happening in some environments. Maybe we should wait longer to configure quartz? What do you think, @MatejBalantic?

**Comment by monitorjbl** [comment] 2015-01-10 18:47
I'm a little curious as to why the switch to simple delaying was made in that commit. It looked like the method that it replaced was more reliable, at least at first glance. Would you mind explaining what was going on the time?

**Comment by MatejBalantic** [comment] 2015-01-11 14:15
I tried to use the quatzjob version before that change and it breaks as well, as the code does not account for the fact that failure to connect raises an exception which breaks the whole app as it is not caught. 

I was thinking of making a pull request for it, but I can not make it this weekend. For now I'm just not using production environment on my machine

**Comment by csokol** [comment] 2015-01-11 18:59
I don't remember why I did that, but I hope I had a good reason :-)

I'll try to reproduce and fix this bug during the next week...

**Comment by csokol** [comment] 2015-01-12 11:53
Now I remember why I did that. That code is testing if the application is running by executing requests to the "/" path. But there are times that your application doesn't have a route mapped to "/" and in that case the http request will result in a 404 and that while will run for two minutes and than quartz will not be configured. The easiest solution I found by that time was to define a fixed amount of time to wait.

The simplest solution I see right now is to increase the amount of time to wait and let this value to be configurable through vraptor's environment api.

**Comment by csokol** [comment] 2015-01-12 12:41
Hi @MatejBalantic, can you test mamute now? I've just updated vraptor-quartzjob and I beleive this issue is now fixed.

**Comment by leocwolter** [comment] 2015-01-12 15:05
Why not configure the url that quartz will use to check if the server is up?

**Comment by MatejBalantic** [comment] 2015-01-12 20:01
I tested it and it works. This error only occured on Mac, not on production Ubuntu machine, which looks to be a race condition due to the timing.

I really think extending timing is not the best idea, let's rather work around the actual problem. Can't we just check that the configuration endpoint is there, or even better, just check for any non-500 response (even if it's 404)

**Comment by monitorjbl** [comment] 2015-02-04 15:13
I agree with @MatejBalantic . I would think that looping until ready would be a better workaround. That way, you can easily ensure the system is up even if something is going on with the server and it takes longer than normal to start.

Is there a way to determine when '/' is not mapped? Is it a config option or something like that?

**Comment by cpfeiffer** [comment] 2015-02-04 21:01
I am out of the office until 05.02.2015.

In dringenden F�llen, kontaktieren Sie bitte
Erwin<punkt>Tratar<at>gebit<punkt>de oder
Tom<punkt>Krauss<at>gebit<punkt>de.


Note: This is an automated response to your message  "Re: [mamute] Maven
coming back with an error on clean install (#127)" sent on 04.02.2015
16:13:26.

This is the only notification you will receive while this person is away.

**Comment by leocwolter** [comment] 2015-05-18 23:35
Since this is a quartzjob issue, I'll close this one.

Thanks!

**Closed by leocwolter** 2015-05-18 23:35 UTC
